primary:
  persistence:
    enabled: false
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
      ephemeral-storage: 200Mi
    requests:
      cpu: 100m
      memory: 128Mi
      ephemeral-storage: 200Mi
  livenessProbe:
    failureThreshold: 30
    initialDelaySeconds: 300
