primary:
  persistence:
    enabled: false
  resources:
    limits:
      cpu: 1000m
      memory: 512Mi
      ephemeral-storage: 2048Mi
    requests:
      cpu: 1000m
      memory: 512Mi
      ephemeral-storage: 1024Mi
  livenessProbe:
    failureThreshold: 30
    initialDelaySeconds: 300
